### ISSUE TITLE
Meta: 🗣️ Malte-App Contact Form

### ISSUE THREAD

**Issue by sarahsporck** [digitalfabrik/integreat-app#2315]
As a person living in a Malteser accomodation I want to contact someone via the integreat app such that they can help/contact me.

## Acceptance Criteria:

- [ ] A form with the correct fields is rendered
- [ ] Form can be rendered onto any specific page
- [ ] the form can be submitted to Zammad

## Technical Tasks:

- [x] #2313 
- [x] #2318 
- [x] #2316 
- [x] Contact form native

**Comment by sarahsporck** [comment]
Malte App needs to implement Contact Forms that interact with a back end Zammad.

The CMS will provide an API endpoint that informs the app that a form should be embedded into a specific page. This will include a form ID, which will usually be the title of the German translation and a Zammad URL.

The app has to render a form with the following fields that are visible to the user:
```
Zimmernummer:

Name:

[x] Ich möchte digital kontaktiert werden:
---- 8< -----
(Eins von beiden Pflicht, wenn Häkchen gesetzt. Ansonsten verschwindet die Auswahl.)

Telefonnummer:

E-Mail:
---- >8 -----

Ich möchte von einer [männlichen/weiblichen/egal] Person kontaktiert werden.

Optional Textfeld: 
```
The app has to request a token from Zammad via the [form_config endpoint](https://helpdesk.integreat-app.de/api/v1/form_config) (https://community.zammad.org/t/submit-form-from-custom-ui/7497). The form has to be submitted as multipart/form-data (or maybe even as JSON, we need to test this) which includes the token to [submit](https://helpdesk.integreat-app.de/api/v1/form_submit)

Before submitting, the app needs to render all fields into a single formatted string. The current language should also be included into the string.

More Info:

- https://nextcloud.tuerantuer.org/index.php/f/4782047
- https://nextcloud.tuerantuer.org/index.php/f/3906203

We can discuss this in a session on T31K on 2023-09-22/23
